server:
  port: ${PORT:8762}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-acl
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false  # Ahora usa nombres tal como están en Eureka
      routes:
        - id: MS-BOOKS-CATALOGUE  # Ahora coincide con el nombre en Eureka
          uri: lb://MS-BOOKS-CATALOGUE
          predicates:
            - Path=/ms-books-catalogue/**
          filters:
            - StripPrefix=1
        - id: MS-BOOKS-PAYMENTS  # Asegurar que coincide con el nombre en Eureka
          uri: lb://MS-BOOKS-PAYMENTS
          predicates:
            - Path=/ms-books-payments/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            allow-credentials: true

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: '*'
