server:
  port: ${PORT:8762}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761/eureka}

spring:
  application:
    name: gateway-acl
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-books-catalogue
          uri: lb://ms-books-catalogue
          predicates:
            - Path=/ms-books-catalogue/**
          filters:
            - StripPrefix=1
        - id: ms-books-payments
          uri: lb://ms-books-payments
          predicates:
            - Path=/ms-books-payments/**
          filters:
            - RewritePath=/ms-books-payments/(?<remaining>.*), /$\{remaining}
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            allow-credentials: true

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: '*'
