server:
  port: ${PORT:8762}

spring:
  application:
    name: gateway-acl
  cloud:
    gateway:
      routes:
        - id: ms-books-catalogue
          uri: https://ms-books-catalogue-production.up.railway.app
          predicates:
            - Path=/api/libros/**
          filters:
            - StripPrefix=1
        - id: ms-books-payments
          uri: lb://ms-books-payments
          predicates:
            - Path=/ms-books-payments/**
          filters:
            - RewritePath=/ms-books-payments/(?<remaining>.*), /$\{remaining}
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
            allow-credentials: true

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: '*'
